site_name: Algorithm Study
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate 
    - navigation.top

  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  plugins:
    - search:
      lang: en

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/giraycoskun
    - icon: fontawesome/brands/github
      link: https://giraycoskun.github.io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/giraycoskun/


nav:
  - Intro: index.md
  - Euler Project: euler-project.md
  

