#Euler Project
#Problem 2 // 04.07.2019

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


fib1 = 1
fib2 = 2

sum_even_fib = 0
nUperLevel = 4000000
nUperLevel = input("Please enter an upper level: ")
if nUperLevel.isdigit():
    nUperLevel = int(nUperLevel)
    while(fib1 < nUperLevel and fib2 < nUperLevel):
        if(fib2%2==0):
            sum_even_fib += fib2
        temp = fib1+fib2
        fib1 = fib2
        fib2 = temp
        
    print("Sum of even valued fibonacci terms which do not exceed four million: ", sum_even_fib )

else:
    print("Invalid entry")
    
input("\nBye Bye")
#Giray Coskun

